// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/**
 * Vercel runs `postinstall` → `prisma generate` during `npm install`, before
 * project env vars are always available. `prisma generate` does not connect to
 * the DB; it only needs a syntactically valid URL. At build time, set
 * `DATABASE_URL` so `prisma migrate deploy` hits your real database.
 */
const PRISMA_GENERATE_PLACEHOLDER =
  "postgresql://prisma_generate_placeholder:prisma_generate_placeholder@127.0.0.1:5432/postgres?schema=public";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL?.trim() || PRISMA_GENERATE_PLACEHOLDER,
  },
});
