// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use `env()` so the URL is resolved when the CLI runs (required for `migrate deploy` on Vercel).
    url: env("DATABASE_URL"),
  },
});
